steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--progress=plain', '-t', 'gcr.io/$PROJECT_ID/h2ox-w2w','.']
- name: 'bash'
  args: ['ls', '..', '-a']
- name: 'bash'
  args: ['ls', '.', '-aR']
- name: 'bash'
  args: ['echo','$PWD']
images:
- 'gcr.io/$PROJECT_ID/h2ox-w2w'