steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--progress=plain', '-t', 'gcr.io/$PROJECT_ID/h2ox-w2w','.']
- name: 'bash'
  args: ['ls', '-laR']
images:
- 'gcr.io/$PROJECT_ID/h2ox-w2w'